DreamCrusherMLM/Controllers/AdminProfileController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DreamCrusherMLM.Models;
using DreamCrusherMLM.Filter;
using System.Data;
using System.Web.UI.WebControls;
using System.Web.UI;

namespace DreamCrusherMLM.Controllers
{
    public class AdminProfileController : AdminBaseController
    {
        #region BoosterAchieverCurrent

        public ActionResult BoosterAchieverCurrent()
        {
            return View();
        }
        [HttpPost]
        [ActionName("BoosterAchieverCurrent")]
        [OnAction(ButtonName = "GetDetails")]
        public ActionResult BoosterAchieverCurrent(Reports model)
        {
            List<Reports> lst = new List<Reports>();

            model.FromDate = string.IsNullOrEmpty(model.FromDate) ? null : Common.ConvertToSystemDate(model.FromDate, "dd/MM/yyyy");
            model.ToDate = string.IsNullOrEmpty(model.ToDate) ? null : Common.ConvertToSystemDate(model.ToDate, "dd/MM/yyyy");
            DataSet ds = model.GetBoosterAchieverCurrent();
            ViewBag.Total = "0";
            if (ds != null && ds.Tables.Count > 0 && ds.Tables[0].Rows.Count > 0)
            {
                foreach (DataRow r in ds.Tables[0].Rows)
                {
                    Reports obj = new Reports();
                    obj.Name = r["Name"].ToString();
                    obj.LoginId = r["LoginId"].ToString();
                    obj.AchievementDate = r["AchievementDate"].ToString();
                    obj.PermanentDate = (r["PermanentDate"].ToString());
                    obj.Amount = (r["Amount"].ToString());
                    obj.EncryptName = Crypto.Encrypt((r["Name"].ToString()));
                    ViewBag.Total = Convert.ToDecimal(ViewBag.Total) + Convert.ToDecimal(r["Amount"].ToString());

                    lst.Add(obj);
                }
                model.lstassociate = lst;


            }
            return View(model);
        }

        #endregion

        #region PayBoosterAchieverCurrent

        public ActionResult PayBoosterAchieverCurrent()
        {
            #region ddlLeg
            List<SelectListItem> ddlLeg = Common.Leg();
            ViewBag.ddlLeg = ddlLeg;
            #endregion ddlLeg
            Reports model = new Reports();
            List<Reports> lst = new List<Reports>();
            // model.LoginId = Session["LoginId"].ToString();
            model.FromDate = string.IsNullOrEmpty(model.FromDate) ? null : Common.ConvertToSystemDate(model.FromDate, "dd/MM/yyyy");
            model.ToDate = string.IsNullOrEmpty(model.ToDate) ? null : Common.ConvertToSystemDate(model.ToDate, "dd/MM/yyyy");
            DataSet ds = model.GetPayBoosterAchieverCurrent();

            if (ds != null && ds.Tables.Count > 0 && ds.Tables[0].Rows.Count > 0)
            {
                foreach (DataRow r in ds.Tables[0].Rows)
                {
                    Reports obj = new Reports();
                    obj.Name = r["Name"].ToString();
                    obj.LoginId = r["LoginId"].ToString();
                    obj.MemberAccNo = r["MemberAccNo"].ToString();
                    obj.IFSCCode = (r["IFSCCode"].ToString());
                    obj.BankName = (r["MemberBankName"].ToString());
                    obj.MaturityDate = (r["MaturityDate"].ToString());
                    obj.Amount = (r["Amount"].ToString());
                    obj.Description = (r["Description"].ToString());
                    obj.Pk_PaidBoosterId = (r["Pk_PaidBoosterId"].ToString());
                    obj.TransactionDate = (r["TransactionDate"].ToString());
                    obj.TransactionNo = (r["TransactionNo"].ToString());
                    lst.Add(obj);
                }
                model.lstassociate = lst;
            }
            Session["Lst"] = model.lstassociate;
            return View(model);
        }
        [HttpPost]
        [ActionName("PayBoosterAchieverCurrent")]
        [OnAction(ButtonName = "GetDetails")]
        public ActionResult PayBoosterAchieverCurrent(Reports model)
        {
            #region ddlLeg
            List<SelectListItem> ddlLeg = Common.Leg();
            ViewBag.ddlLeg = ddlLeg;
            #endregion ddlLeg
            List<Reports> lst = new List<Reports>();
            model.FromDate = string.IsNullOrEmpty(model.FromDate) ? null : Common.ConvertToSystemDate(model.FromDate, "dd/MM/yyyy");
            model.ToDate = string.IsNullOrEmpty(model.ToDate) ? null : Common.ConvertToSystemDate(model.ToDate, "dd/MM/yyyy");
            DataSet ds = model.GetPayBoosterAchieverCurrent();
            ViewBag.Total = "0";
            if (ds != null && ds.Tables.Count > 0 && ds.Tables[0].Rows.Count > 0)
            {
                foreach (DataRow r in ds.Tables[0].Rows)
                {
                    Reports obj = new Reports();
                    obj.Name = r["Name"].ToString();
                    obj.LoginId = r["LoginId"].ToString();
                    obj.MemberAccNo = r["MemberAccNo"].ToString();
                    obj.IFSCCode = (r["IFSCCode"].ToString());
                    obj.BankName = (r["MemberBankName"].ToString());
                    obj.MaturityDate = (r["MaturityDate"].ToString());
                    obj.Amount = (r["Amount"].ToString());
                    obj.Description = (r["Description"].ToString());
                    obj.Pk_PaidBoosterId = (r["Pk_PaidBoosterId"].ToString());
                    obj.TransactionDate = (r["TransactionDate"].ToString());
                    obj.TransactionNo = (r["TransactionNo"].ToString());
                    ViewBag.Total = Convert.ToDecimal(ViewBag.Total) + Convert.ToDecimal(r["Amount"].ToString());

                    lst.Add(obj);
                }
                model.lstassociate = lst;
            }
            Session["Lst"] = model.lstassociate;
            return View(model);
        }

        [HttpPost]
        [ActionName("PayBoosterAchieverCurrent")]
        [OnAction(ButtonName = "Export")]
        public ActionResult ExportToExcelBoosterCurrent(Reports model)
        {

            List<Reports> lst = new List<Reports>();
            // model.LoginId = Session["LoginId"].ToString();
            model.FromDate = string.IsNullOrEmpty(model.FromDate) ? null : Common.ConvertToSystemDate(model.FromDate, "dd/MM/yyyy");
            model.ToDate = string.IsNullOrEmpty(model.ToDate) ? null : Common.ConvertToSystemDate(model.ToDate, "dd/MM/yyyy");
            DataSet ds = model.GetPayBoosterAchieverCurrent();

            if (ds != null && ds.Tables.Count > 0 && ds.Tables[0].Rows.Count > 0)
            {
                string filename = "PayBoosterCurrent.xls";
                GridView GridView1 = new GridView();
                ds.Tables[0].Columns.Remove("Pk_PaidBoosterId");
                ds.Tables[0].Columns.Remove("Description");
                ds.Tables[0].Columns.Remove("TransactionNo");
                ds.Tables[0].Columns.Remove("TransactionDate");
                GridView1.DataSource = ds.Tables[0];
                GridView1.DataBind();
                //string style = @" .text { mso-number-format:\@; }  ";
                string style = @"<style> td { mso-number-format:\@; } </style> ";

                Response.Clear();
                // Response.AddHeader("content-disposition", "attachment;filename=MemberDetailsReport.xls");
                Response.AddHeader("Content-Disposition", "attachment; filename=" + filename + "");
                Response.Charset = "";
                Response.Cache.SetCacheability(HttpCacheability.NoCache);
                Response.ContentType = "application/vnd.ms-excel";
                System.IO.StringWriter s_Write = new System.IO.StringWriter();
                System.Web.UI.HtmlTextWriter h_write = new HtmlTextWriter(s_Write);
                GridView1.ShowHeader = true;
                GridView1.RenderControl(h_write);
                Response.Write(style);
                Response.Write(s_Write.ToString());
                Response.End();
                
            }

            return null;
        }

        [HttpPost]
        [ActionName("PayBoosterAchieverCurrent")]
        [OnAction(ButtonName = "Save")]
        public ActionResult PayBoosterAchieverCurrentAction(Reports model)
        {
            string hdrows2 = Request["hdRows2"].ToString();
            string amount = "";
            string description = "";
            string transactiono = "";
            string transactiondate = "";
            string Pk_PaidBoosterId_ = "";
            for (int i = 1; i < int.Parse(hdrows2); i++)
            {
                Pk_PaidBoosterId_ = Request["Pk_PaidBoosterId_ " + i].ToString();
                amount = "";
                description = Request["txtdecription_ " + i].ToString();
                transactiono = Request["txttranno_ " + i].ToString();
                transactiondate = Request["txttransdate_ " + i].ToString();
                model.Amount = amount;
                model.Pk_PaidBoosterId = Pk_PaidBoosterId_;
                model.Description = description;
                model.TransactionNo = transactiono;
                DataSet ds = null;
                if (!string.IsNullOrEmpty(transactiondate))
                {

                    model.TransactionDate = transactiondate;

                    model.AddedBy = Session["Pk_AdminId"].ToString();
                    ds = model.PayBooster();
                }
                if (ds != null && ds.Tables.Count > 0 && ds.Tables[0].Rows.Count > 0)
                {

                    if (ds.Tables[0].Rows[0]["Msg"].ToString() == "1")
                    {

                    }
                    else
                    {
                        // TempData["BoosterPay"] = ds.Tables[0].Rows[0]["ErrorMessage"].ToString();
                    }
                }

            }
            TempData["BoosterPay"] = "Paymnent Done";

DreamCrusherMLM/Views/AdminProfile/AssociateList.cshtml
@model DreamCrusherMLM.Models.Reports
@{
    ViewBag.Title = "AssociateList";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="row">
    <div class="col-sm-12">
        <ol class="breadcrumb">
            <li>
                <i class="clip-home-3"></i>
                <a href="#">
                    Reports
                </a>
            </li>
            <li class="active">
                Associate List
            </li>
        </ol>
    </div>
</div>

<br />
@using (Html.BeginForm("AssociateList", "AdminProfile", FormMethod.Post, new { @id = "form1", enctype = "multipart/form-data" }))
{

    <p style="color:red">
        @TempData["BlockUnblock"]
        @TempData["UpdateProfilebyadmin"]
    </p>

    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                   Associate List
                </div>
                <!-- /.panel-heading -->
                <div class="panel-body">
                    <div class="row">

                        <div class="col-md-12 table-responsive">
                            <div class="row">
                                <div class="col-lg-3">
                                    <div class="form-group">
                                        <label>Login ID </label>
                                        @Html.TextBoxFor(m => m.LoginId, new { @class = "form-control" })
                                    </div>
                                </div>
                                <div class="col-lg-3">
                                    <div class="form-group">
                                        <label>Name </label>
                                        @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
                                    </div>
                                </div>
                                <div class="col-lg-3">
                                    <div class="form-group">
                                        <label>Spill ID</label>
                                        @Html.TextBoxFor(m => m.SponsorId, new { @class = "form-control" })
                                    </div>
                                </div>
                                <div class="col-lg-3">
                                    <div class="form-group">
                                        <label>Spill Name</label>
                                        @Html.TextBoxFor(m => m.SponsorName, new { @class = "form-control" })
                                    </div>
                                </div>
                                <div class="col-lg-3">
                                    <div class="form-group">
                                        <label>From Date</label>
                                        @Html.TextBoxFor(m => m.FromDate, new { @class = "form-control", @readonly = "readonly" })
                                    </div>
                                </div>
                                <div class="col-lg-3">
                                    <div class="form-group">
                                        <label>To Date</label>
                                        @Html.TextBoxFor(m => m.ToDate, new { @class = "form-control", @readonly = "readonly" })
                                    </div>
                                </div>
                                <div class="col-lg-3">
                                    <div class="form-group">
                                        <label>Status</label>
                                        @Html.DropDownListFor(m => m.Status, new SelectList(ViewBag.ddlstatus, "Value", "Text"), new { @class = "form-control" })
                                    </div>
                                </div>
                                <div class="col-lg-3">
                                    <div class="form-group">
                                        <br />
                                        <input type="submit" id="btnSearch" class="btn btn-success pull-left" name="Search" value="Search" />
                                    </div>
                                </div>
                            </div>
                            <table id="example23" class="display nowrap table table-hover table-striped table-bordered" cellspacing="0" width="100%">
                                <thead>
                                    <tr>
                                        <th>Sr No.</th>
                                        <th> Login Id</th>
                                        <th>Password</th>
                                        <th>Name</th>
                                        <th>Spill Id</th>
                                        <th>Spill Name</th>
                                        <th>Joining Date</th>
                                        <th>Mobile No</th>
                                        <th>Email Id</th>
                                        <th></th>
                                        <th></th>
                                        <th></th>
                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @if (Model != null)
                                    {
                                        if (Model.lstassociate != null)
                                        {
                                            int i = 1;
                                            foreach (var Item in Model.lstassociate)
                                            {
                                                <tr class="text-left">
                                                    <td>@i</td>
                                                    <td>@Item.LoginId</td>
                                                    <td>@Item.Password</td>
                                                    <td>@Item.Name</td>
                                                    <td>@Item.SponsorId</td>
                                                    <td>@Item.SponsorName</td>
                                                    <td>@Item.JoiningDate</td>
                                                    <td>@Item.Mobile</td>
                                                    <td>@Item.Email</td>
                                                    <td>
                                                        <a href="/AdminProfile/UpdateAssociateProfile?LoginID=@Item.LoginId" class="btn btn-info">
                                                            Edit
                                                        </a>
                                                    </td>
                                                    <td>
                                                        @if (Item.isBlocked == "False")
                                                        {
                                                            <a href="/AdminProfile/BlockAssociate?LoginID=@Item.LoginId" class="btn btn-danger">
                                                                Block
                                                            </a>
                                                        }
                                                        else
                                                        {
                                                            <a href="/AdminProfile/UnblockAssociate?LoginID=@Item.LoginId" class="btn btn-success">
                                                                Unblock
                                                            </a>
                                                        }
                                                    </td>
                                                    <td>
                                                        @if (Item.Status == "Inactive")
                                                        {
                                                            <a href="/AdminProfile/ActivateUser?FK_UserID=@Item.Fk_UserId" class="btn btn-success" onclick="return confirm('Sure you want to activate this User ?')">
                                                                Activate
                                                            </a>
                                                        }
                                                        else
                                                        {
                                                            <a href="/AdminProfile/DeactivateUser?lid=@Item.LoginId" class="btn btn-danger" onclick="return confirm('Sure you want to deactivate this User ?')">
                                                                Deactivate
                                                            </a>
                                                        }
                                                    </td>
                                                    <td>
                                                        <a href="/AdminProfile/WelcomeLetter?LoginID=@Item.LoginId" class="btn btn-info">
                                                            Print
                                                        </a>
                                                    </td>
                                                </tr>
                                                i++;
                                            }

                                        }
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- content-wrapper ends -->
        <!-- partial:../../partials/_footer.html -->
        <!-- partial -->
    </div>
    <!-- main-panel ends -->
   

}

<script src="../../vendor/jquery/jquery.min.js"></script>
<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
<link rel="stylesheet" type="text/css" href="https://code.jquery.com/ui/1.12.0/themes/smoothness/jquery-ui.css">
<script>

    $('#FromDate').datepicker({
        dateFormat: 'dd/mm/yy',
        changeYear: true,
        changeMonth: true
    });
    $('#ToDate').datepicker({
        dateFormat: 'dd/mm/yy',
        changeYear: true,
        changeMonth: true
    });
</script>

DreamCrusherMLM/Views/AdminProfile/BoosterAchieverCurrent.cshtml
@model DreamCrusherMLM.Models.Reports

@{
    ViewBag.Title = "BoosterAchieverCurrent";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<div class="row">
    <div class="col-sm-12">
        <ol class="breadcrumb">
            <li>
                <i class="clip-home-3"></i>
                <a href="#">
                    Booster
                </a>
            </li>
            <li class="active">
                Booster Achiever
            </li>
        </ol>
    </div>
</div>

<br />
@using (Html.BeginForm("BoosterAchieverCurrent", "AdminProfile", FormMethod.Post, new { @id = "form1", enctype = "multipart/form-data" }))
{

    <p style="color:red">
        @TempData["BlockUnblock"]
        @TempData["UpdateProfilebyadmin"]
    </p>

    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Booster Achiever List
                </div>
                <!-- /.panel-heading -->
                <div class="panel-body">
                    <div class="row">

                        <div class="col-md-12 table-responsive">
                            <div class="row">
                                <div class="col-lg-3">
                                    <div class="form-group">
                                        <label>Login ID </label>
                                        @Html.TextBoxFor(m => m.LoginId, new { @class = "form-control" })
                                    </div>
                                </div>
                                <div class="col-lg-3">
                                    <div class="form-group">
                                        <label>From Date</label>
                                        @Html.TextBoxFor(m => m.FromDate, new { @class = "form-control", @readonly = "readonly" })
                                    </div>
                                </div>
                                <div class="col-lg-3">
                                    <div class="form-group">
                                        <label>To Date</label>
                                        @Html.TextBoxFor(m => m.ToDate, new { @class = "form-control", @readonly = "readonly" })
                                    </div>
                                </div>
                                <div class="col-lg-3">
                                    <div class="form-group">
                                        <br />
                                        <input type="submit" id="btnSearch" class="btn btn-success pull-left" name="Search" value="Search" />
                                    </div>
                                </div>
                            </div>
                            <table id="example23" class="display nowrap table table-hover table-striped table-bordered" cellspacing="0" width="100%">
                                <thead>
                                    <tr>
                                        <th>Sr No.</th>
                                        <th>Login ID</th>
                                        <th>Name</th>
                                        <th>Amount</th>
                                        <th>Achievement Date</th>
                                        <th>Permanent Date</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @if (Model != null)
                                    {
                                        if (Model.lstassociate != null)
                                        {
                                            int i = 1;
                                            foreach (var Item in Model.lstassociate)
                                            {
                                                <tr class="text-left">
                                                    <td>@i</td>
                                                    <td>@Item.LoginId</td>
                                                    <td>@Item.Name</td>
                                                    <td>@Item.Amount</td>
                                                    <td>@Item.AchievementDate</td>
                                                    <td>@Item.PermanentDate</td>
                                                    <td>
                                                        <a href="/Admin/BoosterCertificate?n=@Item.EncryptName" class="btn btn-sm btn-success">Print Certificate</a>
                                                    </td>
                                                </tr>
                                                i++;
                                            }

                                        }
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- content-wrapper ends -->
        <!-- partial:../../partials/_footer.html -->
        <!-- partial -->
    </div>
    <!-- main-panel ends -->


}

<script src="../../vendor/jquery/jquery.min.js"></script>
<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
<link rel="stylesheet" type="text/css" href="https://code.jquery.com/ui/1.12.0/themes/smoothness/jquery-ui.css">
<script>

    $('#FromDate').datepicker({
        dateFormat: 'dd/mm/yy',
        changeYear: true,
        changeMonth: true
    });
    $('#ToDate').datepicker({
        dateFormat: 'dd/mm/yy',
        changeYear: true,
        changeMonth: true
    });
</script>