DreamCrusherMLM/Models/DashBoard.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web;

namespace DreamCrusherMLM.Models
{
    public class DashBoard:Common
    {
        public string JoiningDate { get; set; }
        public string Total { get; set; }

        public string Status { get; set; }
        public string Fk_UserId { get; set; }

        public DataSet GetDashBoardDetails()
        {

            DataSet ds = DBHelper.ExecuteQuery("GetDashBoardDetails");
            return ds;
        }

        public DataSet GetAssociateDashboard()
        {
            SqlParameter[] para = { new SqlParameter("@Fk_UserId",Fk_UserId ) , };
            DataSet ds = DBHelper.ExecuteQuery("GetDashBoardDetailsForAssociate",para);
            return ds;
        }

        public string LoginId { get; set; }


     

        public List<DashBoard> lstmessages { get; set; }

        public string Pk_MessageId { get; set; }

        public string MessageTitle { get; set; }

        public string Message { get; set; }

        public DataSet GetAllMessages()
        {
            SqlParameter[] para = { new SqlParameter("@Fk_UserId", Fk_UserId) };
            DataSet ds = DBHelper.ExecuteQuery("GetMessages", para);
            return ds;
        }


        public string cssclass { get; set; }

        public string MessageBy { get; set; }

        public DataSet SaveMessage()
        {
            SqlParameter[] para = { 
                                      new SqlParameter("@Message", Message),
                                      new SqlParameter("@AddedBy", AddedBy),
                                      new SqlParameter("@MessageBy", MessageBy),
                                      new SqlParameter("@Fk_UserId", Fk_UserId)
                                  };
            DataSet ds = DBHelper.ExecuteQuery("InsertMessage", para);
            return ds;
        }
        public DataSet GetIDCard()
        {
            SqlParameter[] para = {
                                       new SqlParameter("@FK_UserID", Fk_UserId)
                                  };
            DataSet ds = DBHelper.ExecuteQuery("IDCard", para);
            return ds;
        }
        public string ProfilePic { get; set; }

        public string MemberName { get; set; }

        public List<DashBoard> lstinvestment { get; set; }

        public string Amount { get; set; }

        public string ProductName { get; set; }

        public string Month { get; set; }
    }
}

DreamCrusherMLM/Controllers/FranchiseAdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data;
using DreamCrusherMLM.Models;
using DreamCrusherMLM.Filter;
using System.Web.UI.WebControls;
using BusinessLayer;

namespace DreamCrusherMLM.Controllers
{
    public class FranchiseAdminController : FranchiseAdminBaseController
    {
        DataTable dt = new DataTable();

        #region Dashboard
        public ActionResult DashBoard()
        {
            Franchise model = new Franchise();
            DataSet Ds = model.GetDashBoardDetails();

            ViewBag.TotalPurchase = Ds.Tables[0].Rows[0]["Total"].ToString();
            ViewBag.TotalSale = Ds.Tables[0].Rows[1]["Total"].ToString();
            ViewBag.TotalRequest = Ds.Tables[0].Rows[2]["Total"].ToString();
            ViewBag.TotalApprovedRequest = Ds.Tables[0].Rows[3]["Total"].ToString();
            ViewBag.TotalRejectedRequest = Ds.Tables[0].Rows[4]["Total"].ToString();
            ViewBag.TotalFranchiseSale = Ds.Tables[0].Rows[5]["Total"].ToString();
            ViewBag.TotalStock = Ds.Tables[0].Rows[6]["Total"].ToString();
            ViewBag.SupplierBalance = Ds.Tables[0].Rows[6]["Total"].ToString();
            return View(model);
        }
        public ActionResult SalePurchaseDetails()
        {
            List<Franchise> dataList = new List<Franchise>();
            DataSet Ds = new DataSet();
            DataTable dt = new DataTable();
            Franchise model = new Franchise();

            Ds = model.GetDashBoardDetails();
            if (Ds.Tables.Count > 0)
            {
                ViewBag.TotalUsers = Ds.Tables[1].Rows.Count;
                int count = 0;
                foreach (DataRow dr in Ds.Tables[1].Rows)
                {
                    Franchise details = new Franchise();


                    details.Total = (dr["Total"].ToString());
                    details.Status = (dr["Status"].ToString());


                    dataList.Add(details);

                    count++;
                }
            }
            return Json(dataList, JsonRequestBehavior.AllowGet);
        }
        public ActionResult GetPayoutStatus()
        {
            List<Franchise> dataList = new List<Franchise>();
            DataSet Ds = new DataSet();
            DataTable dt = new DataTable();
            Franchise newdata = new Franchise();

            Ds = newdata.GetDashBoardDetails();
            if (Ds.Tables.Count > 0)
            {
                ViewBag.TotalUsers = Ds.Tables[2].Rows.Count;
                int count = 0;
                foreach (DataRow dr in Ds.Tables[2].Rows)
                {
                    Franchise details = new Franchise();


                    details.Total = (dr["Total"].ToString());
                    details.Status = (dr["Status"].ToString());


                    dataList.Add(details);

                    count++;
                }
            }
            return Json(dataList, JsonRequestBehavior.AllowGet);
        }
        public ActionResult GetJoiningDeatils()
        {
            List<Franchise> dataList = new List<Franchise>();
            DataSet Ds = new DataSet();
            DataTable dt = new DataTable();
            Franchise newdata = new Franchise();

            Ds = newdata.GetDashBoardDetails();
            if (Ds.Tables.Count > 0)
            {
                ViewBag.TotalUsers = Ds.Tables[3].Rows.Count;
                int count = 0;
                foreach (DataRow dr in Ds.Tables[3].Rows)
                {
                    Franchise details = new Franchise();


                    details.Total = (dr["Total"].ToString());
                    details.Month = (dr["Month"].ToString());


                    dataList.Add(details);

                    count++;
                }
            }
            return Json(dataList, JsonRequestBehavior.AllowGet);
        }
        #endregion

        public ActionResult GetSponserDetails(string ReferBy)
        {
            Common obj = new Common();
            obj.ReferBy = ReferBy;
            DataSet ds = obj.GetMemberDetailsForSale();
            if (ds != null && ds.Tables.Count > 0 && ds.Tables[0].Rows.Count > 0)
            {
                if (ds.Tables[0].Rows[0][0].ToString() == "1")
                {
                    obj.DisplayName = ds.Tables[0].Rows[0]["FullName"].ToString();
                    obj.Result = "Yes";
                }
                else if (ds.Tables[0].Rows[0][0].ToString() == "0")
                {
                    obj.Result = ds.Tables[0].Rows[0]["ErrorMessage"].ToString();
                }
            }
            else { obj.Result = "Invalid Franshide Id"; }
            return Json(obj, JsonRequestBehavior.AllowGet);
        }

        #region FranchiseRegistration

        public ActionResult Registration(string id)
        {
            #region BindFranchiseType
            Common obj = new Common();
            List<SelectListItem> ddlFranchiseType = new List<SelectListItem>();
            DataSet ds1 = obj.BindFranchiseType();
            if (ds1 != null && ds1.Tables.Count > 0 && ds1.Tables[0].Rows.Count > 0)
            {
                int count = 0;
                foreach (DataRow r in ds1.Tables[0].Rows)
                {
                    if (count == 0)
                    {
                        ddlFranchiseType.Add(new SelectListItem { Text = "Select", Value = "0" });
                    }
                    ddlFranchiseType.Add(new SelectListItem { Text = r["FranchiseType"].ToString(), Value = r["PK_FranchiseTypeID"].ToString() });
                    count++;
                }
            }

            ViewBag.ddlFranchiseType = ddlFranchiseType;

            #endregion
            if (id != null)
            {
                Franchise model = new Franchise();
                model.PK_FranchiseID = Crypto.Decrypt(id);
                DataSet ds = model.FranchiseList();
                if (ds != null && ds.Tables[0].Rows.Count > 0)
                {
                    model.PK_FranchiseID = ds.Tables[0].Rows[0]["PK_FranchsieID"].ToString();
                    model.ReferBy = ds.Tables[0].Rows[0]["AssociateLoginId"].ToString();
                    model.DisplayName = ds.Tables[0].Rows[0]["FirstName"].ToString();
                    model.FranchiseType = ds.Tables[0].Rows[0]["FK_FranchiseTypeID"].ToString();
                    model.FirmName = ds.Tables[0].Rows[0]["FirmName"].ToString();
                    model.FranchiseName = ds.Tables[0].Rows[0]["FranchiseName"].ToString();
                    model.Contact = ds.Tables[0].Rows[0]["Contact"].ToString();
                    model.Email = ds.Tables[0].Rows[0]["Email"].ToString();
                    model.AdharNo = ds.Tables[0].Rows[0]["AdharNo"].ToString();
                    model.PAN = ds.Tables[0].Rows[0]["PAN"].ToString();
                    model.GSTNo = ds.Tables[0].Rows[0]["GSTNo"].ToString();
                    model.PinCode = ds.Tables[0].Rows[0]["Pincode"].ToString();
                    model.Address = ds.Tables[0].Rows[0]["Address"].ToString();
                    model.State = ds.Tables[0].Rows[0]["State"].ToString();
                    model.City = ds.Tables[0].Rows[0]["City"].ToString();
                }
                return View(model);
            }
            return View();
        }
        [HttpPost]
        [ActionName("FranchiseRegistration")]
        [OnAction(ButtonName = "btnRegister")]
        public ActionResult FranchiseRegistrationAction(Franchise model)
        {
            try
            {
                Random rnd = new Random();
                string pass = rnd.Next(111111, 999999).ToString();
                model.Password = Crypto.Encrypt(pass);
                model.AddedBy = Session["FranchiseAdminID"].ToString();
                DataSet ds = model.FranchiseRegistration();
                if (ds != null && ds.Tables.Count > 0)
                {
                    if (ds.Tables[0].Rows[0]["MSG"].ToString() == "1")
                    {
                        TempData["Class"] = "alert alert-success";
                        TempData["Franchise"] = "Franchise Registation successfull. Login ID : " + ds.Tables[0].Rows[0]["LoginID"].ToString() + "\nPassword : " + Crypto.Decrypt(ds.Tables[0].Rows[0]["Password"].ToString());

                        string passwrd = Crypto.Decrypt(ds.Tables[0].Rows[0]["Password"].ToString());
                        string loginid = Crypto.Decrypt(ds.Tables[0].Rows[0]["LoginID"].ToString());
                        string mob = model.Contact;

                        try
                        {
                            string str = "Dear " + model.FranchiseName + ", You have been successfully registered as Dream Crushers Franchise !Your Login ID is " + ds.Tables[0].Rows[0]["LoginID"].ToString() + " and Password is  " + Crypto.Decrypt(ds.Tables[0].Rows[0]["Password"].ToString() + ".");
                            //string str2 = BLSMS.Registration(ds.Tables[0].Rows[0]["Name"].ToString(), ds.Tables[0].Rows[0]["LoginId"].ToString(), Crypto.Decrypt(ds.Tables[0].Rows[0]["Password"].ToString()));
                            BLSMS.SendSMSNew(mob, str);
                        }
                        catch { }


                    }
                    else if (ds.Tables[0].Rows[0]["MSG"].ToString() == "0")
                    {
                        TempData["Class"] = "alert alert-danger";
                        TempData["Franchise"] = ds.Tables[0].Rows[0]["ErrorMessage"].ToString();
                    }
                }
            }
            catch (Exception ex)
            {
                TempData["Class"] = "alert alert-danger";
                TempData["Franchise"] = ex.Message;
            }
            return RedirectToAction("Registration");
        }
        [HttpPost]
        [ActionName("FranchiseRegistration")]
        [OnAction(ButtonName = "btnUpdate")]

DreamCrusherMLM/Views/FranchiseAdmin/ChangeFranchisePassword.cshtml
@model DreamCrusherMLM.Models.Franchise

@{
    ViewBag.Title = "ChangeFranchisePassword";
    Layout = "~/Views/Shared/FranchiseMasterLayout.cshtml";
}
<div class="row">
    <div class="col-lg-12">
        <br />
        @*<h4 class="page-header">Change Associate Password</h4>*@
    </div>
    <!-- /.col-lg-12 -->
</div>

@using (Html.BeginForm("ChangeFPassword", "FranchiseAdmin", FormMethod.Post, new { @id = "form1", enctype = "multipart/form-data" }))
{


    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Change Franchise Password
                    <br />
                    <p style="color: red">@TempData["ChangeFpassword"] </p>
                </div>
                <!-- /.panel-heading -->
                <div class="panel-body">

                    <div class="row">
                       
                        <div class="col-md-4">
                            <div class="form-group">
                                Login Id <span style="color: red">*</span>
                                @Html.TextBoxFor(m => m.LoginID, new { @class = "form-control", @Placeholder = "Login Id", @onchange = "getmembername(this);" })
                                @Html.ValidationMessageFor(m => m.LoginID)
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                Name <span style="color: red">*</span>
                                <span id="txtname" style="color: blue" class="form-control pull-right"></span>
                            </div>
                        </div>


                        <div class="col-md-4">
                            <div class="form-group">
                                New Password <span style="color: red">*</span>
                                @Html.PasswordFor(m => m.Password, new { @class = "form-control", @Placeholder = "New Password" })
                                @Html.ValidationMessageFor(m => m.Password)
                            </div>
                        </div>
                    </div>
                    
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <input class="btn btn-success pull-left" onclick="return validateform()" type="submit" value="Change Password" />
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
}
<script>
    function validateform() {
        $(".errortext").removeClass("errortext");
        if ($('#LoginID').val() == '') {
            $("#LoginID").addClass('errortext');
            $('#LoginID').focus();
            return false;
        }
        if ($('#Password').val() == '') {
            $("#Password").addClass('errortext');
            $('#Password').focus();
            return false;
        }
        return true;
    }
    function getmembername() {
        debugger;
        var LoginID = $('#LoginID').val();
        $.ajax({
            url: '/FranchiseAdmin/GetFranchiseName',
            type: "GET",
            dataType: "JSON",
            data: { LoginID: LoginID },
            success: function (data) {
                debugger;
                if (data.Result == "yes") {
                    $('#txtname').html(data.FranchiseName);

                    //divname.style.display = "block";
                } else  {
                    alert("Invalid Id");
                    $('#txtname').html("");
                    $('#LoginID').val("");

                }
            }
        });
    }
</script>
<style>
    .errortext {
        border: 1px solid red !important;
        background-color: #fff0f0 !important;
    }
</style>

DreamCrusherMLM/Views/FranchiseAdmin/FranchiseList.cshtml
@model DreamCrusherMLM.Models.Franchise

@{
    ViewBag.Title = "FranchiseList";
    Layout = "~/Views/Shared/FranchiseMasterLayout.cshtml";
}

<div class="row">
    <div class="col-sm-12">
        <ol class="breadcrumb">
            <li>
                <i class="clip-home-3"></i>
                <a href="#">
                    Franchise
                </a>
            </li>
            <li class="active">
                Franchise List
            </li>
        </ol>
    </div>
</div>

<br />
@using (Html.BeginForm("FranchiseList", "FranchiseAdmin", FormMethod.Post, new { @id = "form1", name = "formKYC" }))
{
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Franchise List
                 @*   <a href="/FranchiseAdmin/Registration" class="btn btn-sm btn-primary link pull-right">New Franchise Registration</a>*@
                </div>
                <p style="color:red">
                    @TempData["FranchiseList"]

                </p>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-md-3">
                            Login Id
                            @Html.TextBoxFor(m => m.LoginID, new { @class = "form-control", @placeholder = "Login Id" })
                        </div>
                        <div class="col-md-3">
                            Firm Name
                            @Html.TextBoxFor(m => m.FirmName, new { @class = "form-control", @placeholder = "Firm Name" })
                        </div>
                        <div class="col-md-3">
                            Franchise Name
                            @Html.TextBoxFor(m => m.FranchiseName, new { @class = "form-control", @placeholder = "Franchise Name" })
                         
                        </div>

                        <div class="col-md-3">
                            <br />
                            <input type="submit" class="btn btn-info" value="Search" name="Search" />
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-12 table-responsive">
                            <table id="example23" class="display nowrap table table-hover table-striped table-bordered" cellspacing="0" width="100%">
                                <thead>
                                    <tr>
                                        <th>Sr No.</th>
                                        <th>Login ID</th>
                                        <th>Password</th>
                                        <th>Firm Name</th>
                                        <th>Franchise Name</th>
                                        <th>Contact</th>
                                        <th>Email</th>
                                        <th>PAN No</th>
                                        <th>Adhar No</th>
                                        <th>GSTNo</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @if (Model != null)
                                    {
                                        if (Model.lstFranchise != null)
                                        {
                                            int i = 1;
                                            foreach (var Item in Model.lstFranchise)
                                            {
                                                <tr class="text-left">
                                                    <td>@i</td>
                                                    <td>@Item.LoginID</td>
                                                    <td>@Item.Password</td>
                                                    <td>@Item.FirmName</td>
                                                    <td>@Item.FranchiseName</td>
                                                    <td>@Item.Contact</td>
                                                    <td>@Item.Email</td>
                                                    <td>@Item.PAN</td>
                                                    <td>@Item.AdharNo</td>
                                                    <td>@Item.GSTNo</td>
                                                    <td>
                                                        <a href="/FranchiseAdmin/DeleteFranchise?id=@Item.EncryptKey" onclick="return confirm('Are you sure you want to delete this Franchise ?');" class="btn btn-danger pull-right" >Delete</a>
                                                        <a href="/FranchiseAdmin/Registration?id=@Item.EncryptKey" class="btn btn-primary pull-right">Edit</a>
                                                    </td>
                                                </tr>

                                                i++;
                                            }
                                        }
                                    }


                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

DreamCrusherMLM/Views/FranchiseAdmin/KitRequestDetails.cshtml
@model DreamCrusherMLM.Models.Franchise

@{
    ViewBag.Title = "KitRequestDetails";
    Layout = "~/Views/Shared/FranchiseMasterLayout.cshtml";
}

@using (Html.BeginForm("KitRequestDetails", "FranchiseAdmin", FormMethod.Post, new { @id = "form1", name = "formKYC" }))
{
    if (TempData["KRequestApprovedA"] != null)
    {
        <div class="@TempData["Class"]">
            @TempData["KRequestApprovedA"]
        </div>
    }
    <div class="row">
        <div class="col-md-12">
            <br />
        </div>
    </div>
    <div class="row">
        <div class="col-md-4">
            Requested Qty
            @Html.TextBoxFor(m => m.ApprovedQuantity, new { @class = "form-control", @readonly = "readonly" })
        </div>

        <div class="col-lg-4">
            <div class="form-group">
                Quantity &nbsp;<span style="color:red">*</span>
                @Html.TextBoxFor(m => m.Quantity, new { @class = "form-control", @placeholder = "Quantity", @onchange = "return validateQty(this);", @onkeypress = "return isNumberKey(event);" })
                @Html.HiddenFor(m => m.RequestID)
                @Html.HiddenFor(m => m.KitID)
                @Html.HiddenFor(m => m.LoginID)
                <input type="hidden" id="hdqty" />
                <input type="hidden" id="hdreqqty" />
                <input type="hidden" id="hdkitid" />
            </div>
        </div>
    </div>
    <div class="row">
        <table class="display nowrap table table-hover table-striped table-bordered" cellspacing="0" width="100%">
            <thead>
                <tr>
                    <th>Product Name</th>
                    <th>Batch Name</th>
                    <th>Stock</th>
                    <th>Quantity </th>
                </tr>
            </thead>
            <tbody id="tblData">
                @if (Model != null)
                {
                    if (Model.lstRequest != null)
                    {
                        var i = 0;
                        foreach (var item in Model.lstRequest)
                        {
                            <tr>
                                <td>
                                    @item.ProductName
                                    <input type="hidden" id="hdProductID_@i" name="hdProductID_@i" value="@item.ProductID" />
                                </td>
                                <td>
                                    @Html.DropDownList("ddlBatchNo_" + i, new SelectList(ViewBag.ddlBatch, "Value", "Text"), new { @class = "form-control", @onchange= "return checkStock(this);" })
                                </td>
                                <td>
                                    @*@item.StockID*@
                                    <span id="spStockBatchWise_@i"></span>
                                </td>
                                <td>
                                    <span id="spQty_@i">@item.Quantity</span>
                                </td>
                            </tr>
                            i++;
                        }
                        <input type="hidden" name="hdRows" id="hdRows" value="@i" />
                    }
                }
            </tbody>
        </table>
        <div class="col-md-9">
            <div class="form-group">
                <p style="color:red;font-size:large">NOTE : It is mandatory to select all records to Approve request.</p>
            </div>
        </div>
        <div class="col-md-3">
            <div class="form-group">
                <input type="submit" class="btn btn-sm btn-success" name="btnApprove" value="Approve" onclick="return validateForm();" />
            </div>
        </div>
    </div>
}

<script src="../../vendor/jquery/jquery.min.js"></script>
<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
<link rel="stylesheet" type="text/css" href="https://code.jquery.com/ui/1.12.0/themes/smoothness/jquery-ui.css">

<script>

    function validateForm() {
        if ($('#Quantity').val() == '') {
            $("#Quantity").addClass('errortext');
            $('#Quantity').focus();
            return false;
        }
        if ($('#Quantity').val() == '0') {
            $("#Quantity").addClass('errortext');
            $('#Quantity').focus();
            return false;
        }
    }

    function isNumberKey(evt) {
        var charCode = (evt.which) ? evt.which : event.keyCode
        if (charCode > 31 && (charCode < 48 || charCode > 57))
            return false;
        return true;
    }

    function validateQty(apprqty) {
        var qty = apprqty.value;
        var rqty = $("#ApprovedQuantity").val();
        if ((Number)(qty) > (Number)(rqty)) {
            alert("Approved Quantity cannot be greater than requested quantity");
            apprqty.value = "";
            return false;
        }
        else {
            var rowCount = document.getElementById('hdRows').value;

            for (var i = 0; i <= (Number)(rowCount) ; i++)
            {
                document.getElementById('spQty_' + i).innerText = qty;
            }
        }
    }

    function checkStock(ddlBatch) {
        var selectedDDLid = ddlBatch.id;
        var rowIndex = 0;
        if ((Number)(selectedDDLid.length) < 13) {
            rowIndex = selectedDDLid.substring(selectedDDLid.length - 1, selectedDDLid.length);
        }
        else if ((Number)(selectedDDLid.length) < 15) {
            rowIndex = selectedDDLid.substring(selectedDDLid.length - 2, selectedDDLid.length);
        }
        else {
            rowIndex = selectedDDLid.substring(selectedDDLid.length - 3, selectedDDLid.length);
        }
        
        //alert("Selected row : " + rowIndex);

        var bno = ddlBatch.value;
        var pid = document.getElementById('hdProductID_' + rowIndex).value;
        var rqty = $('#ApprovedQuantity').val();
        //alert("PID : " + pid);

        $.ajax({
            url: '/FranchiseAdmin/GetProductStockByBatch',
            type: 'get',
            dataType: 'json',
            data: { 'bno': bno, 'pid': pid, 'rqty': rqty },
            success: function (data) {
                
                if (data.Result == "1") {
                    document.getElementById('spStockBatchWise_' + rowIndex).innerText = data.Status;
                    document.getElementById('spStockBatchWise_' + rowIndex).style.color = "green";
                }
                else if (data.Result == "0") {
                    document.getElementById('spStockBatchWise_' + rowIndex).innerText = data.Status;
                    document.getElementById('spStockBatchWise_' + rowIndex).style.color = "red";
                    ddlBatch.value = "0";
                }
            }
        });
    }

</script>